export const GET_LIST_BY_USER_ID_SUCCESS = 'GET_LIST_BY_USER_ID_SUCCESS';
export const GET_LIST_BY_USER_ID_FAILED = 'GET_LIST_BY_USER_ID_FAILED';

export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILED = 'CREATE_LIST_FAILED';

export const LIST_BY_ID_SUCCESS = 'LIST_BY_ID_SUCCESS';
export const LIST_BY_ID_FAILED = 'LIST_BY_ID_FAILED';

export const LIST_UPDATE_SUCCESS = 'LIST_UPDATE_SUCCESS';
export const LIST_UPDATE_FAILED = 'LIST_UPDATE_FAILED';

export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS';
export const LIST_DELETE_FAILED = 'LIST_DELETE_FAILED';

export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILED = 'CREATE_ITEM_FAILED';

export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILED = 'UPDATE_ITEM_FAILED';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILED = 'DELETE_ITEM_FAILED';

export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILED = 'GET_ITEM_FAILED';

